### ISSUE TITLE
Attachement ActionMethod call

### ISSUE THREAD

**Issue by vivekborse1804** [CiscoDevNet/botkit-template#22] opened 2021-04-15 10:45 UTC
suppose 
We have two separate adaptive cards in two separate files file1 and file2 and their attachment action method like the below 
**_"controller.on('attachmentActions', async (bot, message) "_**
but the issue is when we call first  _**"controller.hears('hi', 'message,direct_message', async (bot, message)"**_  method then all attachment action method is called from all files i.e file1 and file2 but that should not be happened only same class method should be call.

**Comment by dstaudt** [comment] 2021-04-15 11:28
Can you elaborate a bit more on the scenario...ideally with some sample code?

**Comment by vivekborse1804** [comment] 2021-04-15 13:09
File -1 code
controller.hears('hi', 'message,direct_message', async (bot, message){
await bot.reply(message, {
            text: 'WebexBot',
            attachments: [ starterCard]
        })
})

controller.on('attachmentActions', async (bot, message) => {
 await bot.reply(message, "It is Hi attachement");
})

controller.commandHelp.push({ command: 'hi', text: 'WebexBot interactive adaptive cards' });

--------------------
File -2 code
controller.hears('hello', 'message,direct_message', async (bot, message){
 await bot.reply(message, {
            text: 'WebexBot',
            attachments: [ HelloCard]
        })
})

controller.on('attachmentActions', async (bot, message) => {
 await bot.reply(message, "it is Hello attachement");
})
controller.commandHelp.push({ command: 'hello', text: 'WebexBot interactive adaptive cards' });

----------

suppose user send hi then we got adaptivecard which is-starterCard when we click Action.submit 
then result must be  only **_"It is Hi attachement"_**   but i am getting  both replies from  attachment method randomly 

--output--
 **_"it is Hello attachement"_**
**_"It is Hi attachement"_**

**Comment by davidstaudt** [comment] 2021-04-22 22:10
Thanks, I think I understand the issue better...
AFAIK, Botkit by design (or perhaps characterized as a limitation) does not segregate cards/attachmentActions with any respective conversations.  There is one application-global handler for all attachmentActions regardless of which card/space generated the attachmentAction.  As you've defined two separate handlers for the same single global handler, they are both called.
Ideally, the Botkit plumbing would be enhanced to map/store info about cards sent out in a particular conversation, and then use that info to route incoming attachmentActions back into the correct conversation; however that's probably a not insignificant enhancement, so the developer is left to doing that on their own for now, I guess.
In any case, the issue seems to be belong upstream in Botkit, it would be great if you could open an issue there: https://github.com/howdyai/botkit/issues
Closing this for now...

**Closed as completed** 2021-04-22 22:14 UTC

**Comment by vivekborse1804** [comment] 2021-04-23 05:09
Thank for your help ,
Currently I solved this issue with extra condition check but why extra condition ??
 So  it is good to solve the issue  from howdyai Botkit as per your suggestion so will get correct response to  perticular cards conversation.
Thank you for your support.
